// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "app"

// App 应用
type App struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	AppName         string     `gorm:"column:app_name;not null;comment:应用名" json:"app_name"`                                  // 应用名
	AppDesc         *string    `gorm:"column:app_desc;comment:应用描述" json:"app_desc"`                                          // 应用描述
	AppIcon         *string    `gorm:"column:app_icon;comment:应用图标" json:"app_icon"`                                          // 应用图标
	AppType         int32      `gorm:"column:app_type;not null;comment:应用类型（0-得分类，1-测评类）" json:"app_type"`                    // 应用类型（0-得分类，1-测评类）
	ScoringStrategy int32      `gorm:"column:scoring_strategy;not null;comment:评分策略（0-自定义，1-AI）" json:"scoring_strategy"`     // 评分策略（0-自定义，1-AI）
	ReviewStatus    int32      `gorm:"column:review_status;not null;comment:审核状态：0-待审核, 1-通过, 2-拒绝" json:"review_status"`     // 审核状态：0-待审核, 1-通过, 2-拒绝
	ReviewMessage   *string    `gorm:"column:review_message;comment:审核信息" json:"review_message"`                              // 审核信息
	ReviewerID      *int64     `gorm:"column:reviewer_id;comment:审核人 id" json:"reviewer_id"`                                  // 审核人 id
	ReviewTime      *time.Time `gorm:"column:review_time;default:CURRENT_TIMESTAMP;comment:审核时间" json:"review_time"`          // 审核时间
	UserID          int64      `gorm:"column:user_id;not null;comment:创建用户 id" json:"user_id"`                                // 创建用户 id
	CreateTime      time.Time  `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time  `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DeleteAt        int32      `gorm:"column:delete_at;not null;comment:是否删除" json:"delete_at"`                               // 是否删除
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
