// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "post"

// Post 帖子
type Post struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DeleteAt   int32     `gorm:"column:delete_at;not null;comment:是否删除" json:"delete_at"`                               // 是否删除
	Title      string    `gorm:"column:title;not null;comment:标题" json:"title"`                                         // 标题
	Content    string    `gorm:"column:content;not null;comment:内容" json:"content"`                                     // 内容
	Tags       string    `gorm:"column:tags;not null;comment:标签列表（json 数组）" json:"tags"`                                // 标签列表（json 数组）
	ThumbNum   int32     `gorm:"column:thumb_num;not null;comment:点赞数" json:"thumb_num"`                                // 点赞数
	FavourNum  int32     `gorm:"column:favour_num;not null;comment:收藏数" json:"favour_num"`                              // 收藏数
	UserID     int64     `gorm:"column:user_id;not null;comment:创建用户 id" json:"user_id"`                                // 创建用户 id
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
