// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostFavour = "post_favour"

// PostFavour 帖子收藏
type PostFavour struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	PostID     int64     `gorm:"column:post_id;not null;comment:帖子 id" json:"post_id"`                                  // 帖子 id
	UserID     int64     `gorm:"column:user_id;not null;comment:创建用户 id" json:"user_id"`                                // 创建用户 id
}

// TableName PostFavour's table name
func (*PostFavour) TableName() string {
	return TableNamePostFavour
}
