// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuestion = "question"

// Question 题目
type Question struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	QuestionContent *string   `gorm:"column:question_content;comment:题目内容（json格式）" json:"question_content"`                  // 题目内容（json格式）
	AppID           int64     `gorm:"column:app_id;not null;comment:应用 id" json:"app_id"`                                    // 应用 id
	UserID          int64     `gorm:"column:user_id;not null;comment:创建用户 id" json:"user_id"`                                // 创建用户 id
	CreateTime      time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DeleteAt        int32     `gorm:"column:delete_at;not null;comment:是否删除" json:"delete_at"`                               // 是否删除
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
