// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAnswer = "user_answer"

// UserAnswer 用户答题记录
type UserAnswer struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID           int64     `gorm:"column:app_id;not null;comment:应用 id" json:"app_id"`                                    // 应用 id
	AppType         int32     `gorm:"column:app_type;not null;comment:应用类型（0-得分类，1-角色测评类）" json:"app_type"`                  // 应用类型（0-得分类，1-角色测评类）
	ScoringStrategy int32     `gorm:"column:scoring_strategy;not null;comment:评分策略（0-自定义，1-AI）" json:"scoring_strategy"`     // 评分策略（0-自定义，1-AI）
	Choices         *string   `gorm:"column:choices;comment:用户答案（JSON 数组）" json:"choices"`                                   // 用户答案（JSON 数组）
	ResultID        *int64    `gorm:"column:result_id;comment:评分结果 id" json:"result_id"`                                     // 评分结果 id
	ResultName      *string   `gorm:"column:result_name;comment:结果名称，如物流师" json:"result_name"`                               // 结果名称，如物流师
	ResultDesc      *string   `gorm:"column:result_desc;comment:结果描述" json:"result_desc"`                                    // 结果描述
	ResultPicture   *string   `gorm:"column:result_picture;comment:结果图标" json:"result_picture"`                              // 结果图标
	ResultScore     *int32    `gorm:"column:result_score;comment:得分" json:"result_score"`                                    // 得分
	UserID          int64     `gorm:"column:user_id;not null;comment:用户 id" json:"user_id"`                                  // 用户 id
	CreateTime      time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DeleteAt        int32     `gorm:"column:delete_at;not null;comment:是否删除" json:"delete_at"`                               // 是否删除
}

// TableName UserAnswer's table name
func (*UserAnswer) TableName() string {
	return TableNameUserAnswer
}
