// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	Account    string     `gorm:"column:account;not null;comment:账号" json:"account"`                                     // 账号
	Password   string     `gorm:"column:password;not null;comment:密码" json:"password"`                                   // 密码
	Username   string     `gorm:"column:username;not null;default:新用户;comment:用户昵称" json:"username"`                     // 用户昵称
	AvatarURL  string     `gorm:"column:avatar_url;not null;comment:用户头像" json:"avatar_url"`                             // 用户头像
	Gender     int32      `gorm:"column:gender;not null;default:1;comment:性别:1男;2女;3隐藏" json:"gender"`                   // 性别:1男;2女;3隐藏
	UserInfo   string     `gorm:"column:user_info;not null;comment:个人简介" json:"user_info"`                               // 个人简介
	UserRole   int32      `gorm:"column:user_role;not null;default:10;comment:身份:10普通用户;20管理员" json:"user_role"`         // 身份:10普通用户;20管理员
	CreateTime time.Time  `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time  `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DeleteAt   *time.Time `gorm:"column:delete_at;comment:逻辑删除标记" json:"delete_at"`                                      // 逻辑删除标记
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
